package modelo;
// Generated 17 dic 2021 16:02:15 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private DatosId id;
	private Estaciones estaciones;
	private String precipitaciones;
	private BigDecimal temperatura;
	private BigDecimal velocidadViento;

	public Datos() {
	}

	public Datos(DatosId id, Estaciones estaciones, String precipitaciones, BigDecimal temperatura,
			BigDecimal velocidadViento) {
		this.id = id;
		this.estaciones = estaciones;
		this.precipitaciones = precipitaciones;
		this.temperatura = temperatura;
		this.velocidadViento = velocidadViento;
	}

	public DatosId getId() {
		return this.id;
	}

	public void setId(DatosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getPrecipitaciones() {
		return this.precipitaciones;
	}

	public void setPrecipitaciones(String precipitaciones) {
		this.precipitaciones = precipitaciones;
	}

	public BigDecimal getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(BigDecimal temperatura) {
		this.temperatura = temperatura;
	}

	public BigDecimal getVelocidadViento() {
		return this.velocidadViento;
	}

	public void setVelocidadViento(BigDecimal velocidadViento) {
		this.velocidadViento = velocidadViento;
	}

}
