package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private int Datosid;
	private String precipitaciones;
	private Date fecha;
	private Date hora;
	private BigDecimal temperatura;
	private BigDecimal velocidadViento;

	public Datos() {
	}

	public Datos(int Datosid, String precipitaciones, Date fecha, Date hora, BigDecimal temperatura, BigDecimal velocidadViento) {
		this.Datosid = Datosid;
		this.precipitaciones = precipitaciones;
		this.hora = hora;
		this.fecha = fecha;
		this.temperatura = temperatura;
		this.velocidadViento = velocidadViento;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public int getId() {
		return this.Datosid;
	}

	public void setId(int Datosid) {
		this.Datosid = Datosid;
	}

	public String getPrecipitaciones() {
		return this.precipitaciones;
	}

	public void setPrecipitaciones(String precipitaciones) {
		this.precipitaciones = precipitaciones;
	}

	public BigDecimal getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(BigDecimal temperatura) {
		this.temperatura = temperatura;
	}

	public BigDecimal getVelocidadViento() {
		return this.velocidadViento;
	}

	public void setVelocidadViento(BigDecimal velocidadViento) {
		this.velocidadViento = velocidadViento;
	}

}
