package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private int codEspacio;
	private String nombre;
	private String descripcion;
	private Set estaEns = new HashSet(0);
	private Set favoritosEspacioses = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(int codEspacio, String nombre, String descripcion) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public EspaciosNaturales(int codEspacio, String nombre, String descripcion, Set estaEns, Set favoritosEspacioses) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estaEns = estaEns;
		this.favoritosEspacioses = favoritosEspacioses;
	}

	public int getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(int codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getEstaEns() {
		return this.estaEns;
	}

	public void setEstaEns(Set estaEns) {
		this.estaEns = estaEns;
	}

	public Set getFavoritosEspacioses() {
		return this.favoritosEspacioses;
	}

	public void setFavoritosEspacioses(Set favoritosEspacioses) {
		this.favoritosEspacioses = favoritosEspacioses;
	}

}
