package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private int codEspacio;
	private Municipiospueblos municipiospueblos;
	private String nombre;
	private String descripcion;
	private Integer codLocalidad;
	private Set favoritosEspacioses = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(int codEspacio, String nombre, String descripcion) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public EspaciosNaturales(int codEspacio, Municipiospueblos municipiospueblos, String nombre, String descripcion,
			Integer codLocalidad, Set favoritosEspacioses) {
		this.codEspacio = codEspacio;
		this.municipiospueblos = municipiospueblos;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codLocalidad = codLocalidad;
		this.favoritosEspacioses = favoritosEspacioses;
	}

	public int getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(int codEspacio) {
		this.codEspacio = codEspacio;
	}

	public Municipiospueblos getMunicipiospueblos() {
		return this.municipiospueblos;
	}

	public void setMunicipiospueblos(Municipiospueblos municipiospueblos) {
		this.municipiospueblos = municipiospueblos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getCodLocalidad() {
		return this.codLocalidad;
	}

	public void setCodLocalidad(Integer codLocalidad) {
		this.codLocalidad = codLocalidad;
	}

	public Set getFavoritosEspacioses() {
		return this.favoritosEspacioses;
	}

	public void setFavoritosEspacioses(Set favoritosEspacioses) {
		this.favoritosEspacioses = favoritosEspacioses;
	}

}
