package modelo;
// Generated 13 ene 2022 21:43:38 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private int codEspacio;
	private String nombre;
	private String descripcion;
	private Integer codMunicipio;
	private Integer codLocalidad;
	private Set favoritosEspacioses = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(int codEspacio) {
		this.codEspacio = codEspacio;
	}
	
	public EspaciosNaturales(int codEspacio, Municipiospueblos Municipiospueblos, String nombre, String descripcion, Integer codLocalidad) {
		
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codMunicipio = codMunicipio;
		this.codLocalidad = codLocalidad;
		
	}


	public EspaciosNaturales(int codEspacio, String nombre, String descripcion, Integer codMunicipio,
			Integer codLocalidad, Set favoritosEspacioses) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codMunicipio = codMunicipio;
		this.codLocalidad = codLocalidad;
		this.favoritosEspacioses = favoritosEspacioses;
	}

	public int getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(int codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public Integer getCodLocalidad() {
		return this.codLocalidad;
	}

	public void setCodLocalidad(Integer codLocalidad) {
		this.codLocalidad = codLocalidad;
	}

	public Set getFavoritosEspacioses() {
		return this.favoritosEspacioses;
	}

	public void setFavoritosEspacioses(Set favoritosEspacioses) {
		this.favoritosEspacioses = favoritosEspacioses;
	}

}
