package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private int codEstacion;
	private Municipiospueblos municipiospueblos;
	private int nombre;
	private double coordenadaX;
	private double coordenadaY;
	private Integer codLocalidad;
	private Set datoses = new HashSet(0);

	public Estaciones() {
	}

	public Estaciones(int codEstacion, Municipiospueblos municipiospueblos, int nombre, double coordenadaX,
			double coordenadaY) {
		this.codEstacion = codEstacion;
		this.municipiospueblos = municipiospueblos;
		this.nombre = nombre;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
	}

	public Estaciones(int codEstacion, Municipiospueblos municipiospueblos, int nombre, double coordenadaX,
			double coordenadaY, Integer codLocalidad, Set datoses) {
		this.codEstacion = codEstacion;
		this.municipiospueblos = municipiospueblos;
		this.nombre = nombre;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
		this.codLocalidad = codLocalidad;
		this.datoses = datoses;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public Municipiospueblos getMunicipiospueblos() {
		return this.municipiospueblos;
	}

	public void setMunicipiospueblos(Municipiospueblos municipiospueblos) {
		this.municipiospueblos = municipiospueblos;
	}

	public int getNombre() {
		return this.nombre;
	}

	public void setNombre(int nombre) {
		this.nombre = nombre;
	}

	public double getCoordenadaX() {
		return this.coordenadaX;
	}

	public void setCoordenadaX(double coordenadaX) {
		this.coordenadaX = coordenadaX;
	}

	public double getCoordenadaY() {
		return this.coordenadaY;
	}

	public void setCoordenadaY(double coordenadaY) {
		this.coordenadaY = coordenadaY;
	}

	public Integer getCodLocalidad() {
		return this.codLocalidad;
	}

	public void setCodLocalidad(Integer codLocalidad) {
		this.codLocalidad = codLocalidad;
	}

	public Set getDatoses() {
		return this.datoses;
	}

	public void setDatoses(Set datoses) {
		this.datoses = datoses;
	}

}
