package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

/**
 * EstaEnId generated by hbm2java
 */
public class EstaEnId implements java.io.Serializable {

	private Municipios municipios;
	private EspaciosNaturales espaciosNaturales;

	public EstaEnId() {
	}

	public EstaEnId(Municipios municipios, EspaciosNaturales espaciosNaturales) {
		this.municipios = municipios;
		this.espaciosNaturales = espaciosNaturales;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstaEnId))
			return false;
		EstaEnId castOther = (EstaEnId) other;

		return ((this.getMunicipios() == castOther.getMunicipios()) || (this.getMunicipios() != null
				&& castOther.getMunicipios() != null && this.getMunicipios().equals(castOther.getMunicipios())))
				&& ((this.getEspaciosNaturales() == castOther.getEspaciosNaturales())
						|| (this.getEspaciosNaturales() != null && castOther.getEspaciosNaturales() != null
								&& this.getEspaciosNaturales().equals(castOther.getEspaciosNaturales())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMunicipios() == null ? 0 : this.getMunicipios().hashCode());
		result = 37 * result + (getEspaciosNaturales() == null ? 0 : this.getEspaciosNaturales().hashCode());
		return result;
	}

}
