package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosEspacios generated by hbm2java
 */
public class FavoritosEspacios implements java.io.Serializable {

	private Integer codFav;
	private EspaciosNaturales espaciosNaturales;
	private Usuarios usuarios;

	public FavoritosEspacios() {
	}

	public FavoritosEspacios(EspaciosNaturales espaciosNaturales, Usuarios usuarios) {
		this.espaciosNaturales = espaciosNaturales;
		this.usuarios = usuarios;
	}

	public Integer getCodFav() {
		return this.codFav;
	}

	public void setCodFav(Integer codFav) {
		this.codFav = codFav;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
