package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosMunicipios generated by hbm2java
 */
public class FavoritosMunicipios implements java.io.Serializable {

	private FavoritosMunicipiosId id;

	public FavoritosMunicipios() {
	}

	public FavoritosMunicipios(FavoritosMunicipiosId id) {
		this.id = id;
	}

	public FavoritosMunicipiosId getId() {
		return this.id;
	}

	public void setId(FavoritosMunicipiosId id) {
		this.id = id;
	}

}
