package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosEspaciosId generated by hbm2java
 */
public class FavoritosEspaciosId implements java.io.Serializable {

	private Usuarios usuarios;
	private EspaciosNaturales espaciosNaturales;

	public FavoritosEspaciosId() {
	}

	public FavoritosEspaciosId(Usuarios usuarios, EspaciosNaturales espaciosNaturales) {
		this.usuarios = usuarios;
		this.espaciosNaturales = espaciosNaturales;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosEspaciosId))
			return false;
		FavoritosEspaciosId castOther = (FavoritosEspaciosId) other;

		return ((this.getUsuarios() == castOther.getUsuarios()) || (this.getUsuarios() != null
				&& castOther.getUsuarios() != null && this.getUsuarios().equals(castOther.getUsuarios())))
				&& ((this.getEspaciosNaturales() == castOther.getEspaciosNaturales())
						|| (this.getEspaciosNaturales() != null && castOther.getEspaciosNaturales() != null
								&& this.getEspaciosNaturales().equals(castOther.getEspaciosNaturales())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuarios() == null ? 0 : this.getUsuarios().hashCode());
		result = 37 * result + (getEspaciosNaturales() == null ? 0 : this.getEspaciosNaturales().hashCode());
		return result;
	}

}
