package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosMunicipios generated by hbm2java
 */
public class FavoritosMunicipios implements java.io.Serializable {

	private Integer codFav;
	private Municipiospueblos municipiospueblos;
	private Usuarios usuarios;

	public FavoritosMunicipios() {
	}

	public FavoritosMunicipios(Municipiospueblos municipiospueblos, Usuarios usuarios) {
		this.municipiospueblos = municipiospueblos;
		this.usuarios = usuarios;
	}

	public Integer getCodFav() {
		return this.codFav;
	}

	public void setCodFav(Integer codFav) {
		this.codFav = codFav;
	}

	public Municipiospueblos getMunicipiospueblos() {
		return this.municipiospueblos;
	}

	public void setMunicipiospueblos(Municipiospueblos municipiospueblos) {
		this.municipiospueblos = municipiospueblos;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
