package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosMunicipiosId generated by hbm2java
 */
public class FavoritosMunicipiosId implements java.io.Serializable {

	private Usuarios usuarios;
	private Municipios municipios;

	public FavoritosMunicipiosId() {
	}

	public FavoritosMunicipiosId(Usuarios usuarios, Municipios municipios) {
		this.usuarios = usuarios;
		this.municipios = municipios;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosMunicipiosId))
			return false;
		FavoritosMunicipiosId castOther = (FavoritosMunicipiosId) other;

		return ((this.getUsuarios() == castOther.getUsuarios()) || (this.getUsuarios() != null
				&& castOther.getUsuarios() != null && this.getUsuarios().equals(castOther.getUsuarios())))
				&& ((this.getMunicipios() == castOther.getMunicipios())
						|| (this.getMunicipios() != null && castOther.getMunicipios() != null
								&& this.getMunicipios().equals(castOther.getMunicipios())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuarios() == null ? 0 : this.getUsuarios().hashCode());
		result = 37 * result + (getMunicipios() == null ? 0 : this.getMunicipios().hashCode());
		return result;
	}

}
