package modelo;
// Generated 13 ene 2022 21:43:38 by Hibernate Tools 5.5.7.Final

/**
 * Localidad generated by hbm2java
 */
public class Localidad implements java.io.Serializable {

	private Integer codLocalidad;
	private Municipiospueblos municipiospueblos;
	private String nombre;

	public Localidad() {
	}

	public Localidad(Municipiospueblos municipiospueblos, String nombre) {
		this.municipiospueblos = municipiospueblos;
		this.nombre = nombre;
	}

	public Integer getCodLocalidad() {
		return this.codLocalidad;
	}

	public void setCodLocalidad(Integer codLocalidad) {
		this.codLocalidad = codLocalidad;
	}

	public Municipiospueblos getMunicipiospueblos() {
		return this.municipiospueblos;
	}

	public void setMunicipiospueblos(Municipiospueblos municipiospueblos) {
		this.municipiospueblos = municipiospueblos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
