package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

/**
 * Localidad generated by hbm2java
 */
public class Localidad implements java.io.Serializable {

	private int codLocalidad;
	private Municipiospueblos municipiospueblos;
	private String nombre;
	private String descripcion;

	public Localidad() {
	}

	public Localidad(int codLocalidad, Municipiospueblos municipiospueblos, String nombre, String descripcion) {
		this.codLocalidad = codLocalidad;
		this.municipiospueblos = municipiospueblos;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public int getCodLocalidad() {
		return this.codLocalidad;
	}

	public void setCodLocalidad(int codLocalidad) {
		this.codLocalidad = codLocalidad;
	}

	public Municipiospueblos getMunicipiospueblos() {
		return this.municipiospueblos;
	}

	public void setMunicipiospueblos(Municipiospueblos municipiospueblos) {
		this.municipiospueblos = municipiospueblos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
