package modelo;
// Generated 13 ene 2022 21:43:38 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipiospueblos generated by hbm2java
 */
public class Municipiospueblos implements java.io.Serializable {

	private int codMunicipio;
	private Provincia provincia;
	private String nombre;
	private String descripcion;
	private Set localidads = new HashSet(0);
	private Set favoritosMunicipioses = new HashSet(0);
	private Set estacioneses = new HashSet(0);

	public Municipiospueblos() {
	}

	public Municipiospueblos(int codMunicipio) {
		this.codMunicipio = codMunicipio;
	}
	
	public Municipiospueblos(int codMunicipio, Provincia provincia, String nombre, String descripcion) {
		
		this.codMunicipio = codMunicipio;
		this.provincia = provincia;
		this.nombre = nombre;
		this.descripcion = descripcion;
		
	}

	public Municipiospueblos(int codMunicipio, Provincia provincia, String nombre, String descripcion, Set localidads,
			Set favoritosMunicipioses, Set estacioneses) {
		this.codMunicipio = codMunicipio;
		this.provincia = provincia;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.localidads = localidads;
		this.favoritosMunicipioses = favoritosMunicipioses;
		this.estacioneses = estacioneses;
	}

	public int getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(int codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set localidads) {
		this.localidads = localidads;
	}

	public Set getFavoritosMunicipioses() {
		return this.favoritosMunicipioses;
	}

	public void setFavoritosMunicipioses(Set favoritosMunicipioses) {
		this.favoritosMunicipioses = favoritosMunicipioses;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

}
