package modelo;
// Generated 13 ene 2022 21:43:38 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private int codProvincia;
	private String nombre;
	private Set municipiospuebloses = new HashSet(0);

	public Provincia() {
	}

	public Provincia(int codProvincia) {
		this.codProvincia = codProvincia;
	}
	
	public Provincia(int codProvincia, String nombre) {
		
		this.codProvincia = codProvincia;
		this.nombre = nombre;
		
	}

	public Provincia(int codProvincia, String nombre, Set municipiospuebloses) {
		this.codProvincia = codProvincia;
		this.nombre = nombre;
		this.municipiospuebloses = municipiospuebloses;
	}

	public int getCodProvincia() {
		return this.codProvincia;
	}

	public void setCodProvincia(int codProvincia) {
		this.codProvincia = codProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipiospuebloses() {
		return this.municipiospuebloses;
	}

	public void setMunicipiospuebloses(Set municipiospuebloses) {
		this.municipiospuebloses = municipiospuebloses;
	}

}
