package modelo;
// Generated 20 dic 2021 19:20:11 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private int nombre;
	private int contraseña;
	private Set favoritosEspacioses = new HashSet(0);
	private Set favoritosMunicipioses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int codUsuario, int nombre, int contraseña) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contraseña = contraseña;
	}

	public Usuarios(int codUsuario, int nombre, int contraseña, Set favoritosEspacioses, Set favoritosMunicipioses) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.favoritosEspacioses = favoritosEspacioses;
		this.favoritosMunicipioses = favoritosMunicipioses;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public int getNombre() {
		return this.nombre;
	}

	public void setNombre(int nombre) {
		this.nombre = nombre;
	}

	public int getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(int contraseña) {
		this.contraseña = contraseña;
	}

	public Set getFavoritosEspacioses() {
		return this.favoritosEspacioses;
	}

	public void setFavoritosEspacioses(Set favoritosEspacioses) {
		this.favoritosEspacioses = favoritosEspacioses;
	}

	public Set getFavoritosMunicipioses() {
		return this.favoritosMunicipioses;
	}

	public void setFavoritosMunicipioses(Set favoritosMunicipioses) {
		this.favoritosMunicipioses = favoritosMunicipioses;
	}

}
