package modelo;
// Generated 17 dic 2021 16:17:04 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private String nombre;
	private String contraseña;
	private Set favoritosMunicipioses = new HashSet(0);
	private Set favoritosEspacioses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int codUsuario, String nombre, String contraseña) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contraseña = contraseña;
	}

	public Usuarios(int codUsuario, String nombre, String contraseña, Set favoritosMunicipioses,
			Set favoritosEspacioses) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.favoritosMunicipioses = favoritosMunicipioses;
		this.favoritosEspacioses = favoritosEspacioses;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public Set getFavoritosMunicipioses() {
		return this.favoritosMunicipioses;
	}

	public void setFavoritosMunicipioses(Set favoritosMunicipioses) {
		this.favoritosMunicipioses = favoritosMunicipioses;
	}

	public Set getFavoritosEspacioses() {
		return this.favoritosEspacioses;
	}

	public void setFavoritosEspacioses(Set favoritosEspacioses) {
		this.favoritosEspacioses = favoritosEspacioses;
	}

}
